/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AuthWidget {
        /**
          * @default '600px'
         */
        "height": string;
        /**
          * @default 'bike.png'
         */
        "image": string;
    }
}
declare global {
    interface HTMLAuthWidgetElement extends Components.AuthWidget, HTMLStencilElement {
    }
    var HTMLAuthWidgetElement: {
        prototype: HTMLAuthWidgetElement;
        new (): HTMLAuthWidgetElement;
    };
    interface HTMLElementTagNameMap {
        "auth-widget": HTMLAuthWidgetElement;
    }
}
declare namespace LocalJSX {
    interface AuthWidget {
        /**
          * @default '600px'
         */
        "height"?: string;
        /**
          * @default 'bike.png'
         */
        "image"?: string;
    }
    interface IntrinsicElements {
        "auth-widget": AuthWidget;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "auth-widget": LocalJSX.AuthWidget & JSXBase.HTMLAttributes<HTMLAuthWidgetElement>;
        }
    }
}
